# Using Gaussian Naive Bayes Algorithm on iris datasets

In [1]:
import numpy as np
import pandas as pd

In [2]:
import seaborn as sns
df=sns.load_dataset("iris")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
x=df.iloc[:,0:4]
y=df.iloc[:,4:5]
print(x,y)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]        species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]


In [4]:
#import train and testing model and spliting
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.70,test_size=0.30,random_state=101)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(105, 4) (105, 1) (45, 4) (45, 1)


In [5]:
#import model and fit
from sklearn.naive_bayes import GaussianNB
GNB=GaussianNB()

GNB.fit(x_train,y_train)

C:\PerfLogs\ANACONDA 3\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [6]:
#predictions
y_pred=GNB.predict(x_test)
y_pred

array(['setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'virginica',
       'versicolor'], dtype='<U10')

In [7]:
#check accuracy , reports and confusion matrix
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9555555555555556
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       0.95      0.95      0.95        20
   virginica       0.92      0.92      0.92        12

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[13  0  0]
 [ 0 19  1]
 [ 0  1 11]]


# Using Bernoli Naive Bayes ALgorithm fit for job is fake or not

In [8]:
df=pd.read_csv("D:\\Datasets\\company_job.csv")
df.head()

Company_job Fake logo
0      Absent       Yes
1     Present        No
2     Present        No
3     Present        No
4      Absent        No

In [9]:
df=df.replace({'Absent':2,'Present':3})

In [10]:
x=df['Company_job'].values.reshape(-1,1)
y=df['Fake logo']
print(x,y)

[[2]
 [3]
 [3]
 [3]
 [2]
 [3]
 [3]
 [2]
 [2]
 [3]
 [3]
 [3]
 [2]
 [3]
 [2]
 [3]
 [3]
 [3]
 [2]
 [3]] 0     Yes
1      No
2      No
3      No
4      No
5      No
6      No
7      No
8      No
9      No
10     No
11     No
12    Yes
13    Yes
14     No
15     No
16     No
17     No
18     No
19     No
Name: Fake logo, dtype: object


In [11]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,random_state=101)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(16, 1) (16,) (4, 1) (4,)


In [12]:
from sklearn.naive_bayes import BernoulliNB

BNB=BernoulliNB()
BNB.fit(x_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [13]:
y_pred=BNB.predict(x_test)
y_pred

array(['No', 'No', 'No', 'No'], dtype='<U3')

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [15]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         4

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

[[4]]


# Using Multinomial Naive Bayes Algorithm fit for Golf datasets

In [16]:
df=pd.read_csv("D:\\Datasets\\PlayGolfdata.csv")
df.head()

OUTLOOK TEMPERATURE HUMIDITY  WINDY PLAY GOLF
0     Rainy         Hot     High  False        No
1     Rainy         Hot     High   True        No
2  Overcast         Hot     High  False       Yes
3     Sunny        Mild     High  False       Yes
4     Sunny        Cool   Normal  False       Yes

In [17]:
df=df.replace({'Rainy':0,'Overcast':1,'Sunny':2,'Hot':1,'Cool':2,'Mild':3,'High':1,'Normal':2,'True':1,'False':0})
df.head()

OUTLOOK  TEMPERATURE  HUMIDITY  WINDY PLAY GOLF
0        0            1         1  False        No
1        0            1         1   True        No
2        1            1         1  False       Yes
3        2            3         1  False       Yes
4        2            2         2  False       Yes

In [18]:
x=df.iloc[:,:4]
y=df.iloc[:,4:]
print(x,y)

    OUTLOOK  TEMPERATURE  HUMIDITY  WINDY
0         0            1         1  False
1         0            1         1   True
2         1            1         1  False
3         2            3         1  False
4         2            2         2  False
5         2            2         2   True
6         1            2         2   True
7         0            3         1  False
8         0            2         2  False
9         2            3         2  False
10        0            3         2   True
11        1            3         1   True
12        1            1         2  False
13        2            3         1   True    PLAY GOLF
0         No
1         No
2        Yes
3        Yes
4        Yes
5         No
6        Yes
7         No
8        Yes
9        Yes
10       Yes
11       Yes
12       Yes
13        No


In [19]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.70,test_size=0.30,random_state=101)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(9, 4) (9, 1) (5, 4) (5, 1)


In [20]:
from sklearn.naive_bayes import MultinomialNB

MNB=MultinomialNB()
MNB.fit(x_train,y_train)

C:\PerfLogs\ANACONDA 3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
y_pred=MNB.predict(x_test)
y_pred

array(['Yes', 'Yes', 'Yes', 'Yes', 'No'], dtype='<U3')

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [23]:
print(confusion_matrix(y_test,y_pred))

[[0 1]
 [1 3]]


In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          No       0.00      0.00      0.00         1
         Yes       0.75      0.75      0.75         4

    accuracy                           0.60         5
   macro avg       0.38      0.38      0.38         5
weighted avg       0.60      0.60      0.60         5



In [25]:
print(accuracy_score(y_test,y_pred))

0.6
